name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: 35.172.199.71
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Navigate to home directory
            cd /home/ubuntu

            # Clone if not already cloned
            if [ ! -d "pm2-practice" ]; then
              git clone https://github.com/smnthjm08/pm2-practice.git pm2-practice
            fi

            cd pm2-practice

            # Pull latest changes
            git pull origin main

            # Install Node (if needed)
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm install node
            nvm use node

            # Install dependencies and build
            npm install
            npm run build

            # Install pm2 with elevated privileges
            sudo npm install -g pm2

            # Start or restart the app
            pm2 start npm --name "next-app" -- run start || pm2 restart next-app
